# German message translation file for plpython
# Copyright (C) 2009 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# Peter Eisentraut <peter_e@gmx.net>, 2009.
#
# Use these quotes: »%s«
#
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 8.4\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2010-08-25 20:38+0000\n"
"PO-Revision-Date: 2010-08-26 21:09+0300\n"
"Last-Translator: Peter Eisentraut <peter_e@gmx.net>\n"
"Language-Team: German <peter_e@gmx.net>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"

#: plpython.c:428 plpython.c:453
msgid "unexpected return value from trigger procedure"
msgstr "unerwarteter Rückgabewert von Triggerprozedur"

#: plpython.c:429
msgid "Expected None or a string."
msgstr "Erwartete None oder eine Zeichenkette."

#: plpython.c:443
msgid ""
"PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""
"PL/Python-Funktion gab in einem DELETE-Trigger \"MODIFY\" zurück -- ignoriert"

#: plpython.c:454
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Erwartete None, \"OK\", \"SKIP\" oder \"MODIFY\"."

#: plpython.c:501
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] wurde gelöscht, kann Zeile nicht ändern"

#: plpython.c:504
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] ist kein Dictionary"

#: plpython.c:523
#, c-format
msgid "name of TD[\"new\"] attribute at ordinal position %d is not a string"
msgstr ""
"Name des Attributs auf Position %d in TD[\"new\"] ist keine Zeichenkette"

#: plpython.c:527
#, c-format
msgid ""
"key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering "
"row"
msgstr ""
"in TD[\"new\"] gefundener Schlüssel »%s« existiert nicht als Spalte in der "
"den Trigger auslösenden Zeile"

#: plpython.c:548
#, c-format
msgid ""
"could not compute string representation of Python object in PL/Python "
"function \"%s\" while modifying trigger row"
msgstr ""
"konnte Zeichenkettendarstellung eines Python-Objekts nicht berechnen, in PL/"
"Python-Funktion »%s«, beim Ändern der Triggerzeile"

#: plpython.c:630
msgid "could not create new dictionary while building trigger arguments"
msgstr ""
"konnte neues Dictionary nicht erzeugen, beim Aufbauen der Triggerargumente"

#: plpython.c:838
msgid "unsupported set function return mode"
msgstr "nicht unterstützter Rückgabemodus für Funktion mit Mengenergebnis"

#: plpython.c:839
msgid ""
"PL/Python set-returning functions only support returning only value per call."
msgstr ""
"PL/Python unterstützt für Funktionen mit Mengenergebnis nur das Zurückgeben "
"von einem Wert pro Aufruf."

#: plpython.c:851
msgid "returned object cannot be iterated"
msgstr "zurückgegebenes Objekt kann nicht iteriert werden"

#: plpython.c:852
msgid "PL/Python set-returning functions must return an iterable object."
msgstr ""
"PL/Python-Funktionen mit Mengenergebnis müssen ein iterierbares Objekt "
"zurückgeben."

#: plpython.c:880
msgid "error fetching next item from iterator"
msgstr "Fehler beim Auslesen des nächsten Elements vom Iterator"

#: plpython.c:898
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "PL/Python-Funktion mit Rückgabetyp »void« hat nicht None zurückgegeben"

#: plpython.c:945
#, c-format
msgid ""
"could not create string representation of Python object in PL/Python "
"function \"%s\" while creating return value"
msgstr ""
"konnte Zeichenkettendarstellung eines Python-Objekts nicht erzeugen, in PL/"
"Python-Funktion »%s«, beim Erzeugen des Rückgabewerts"

#: plpython.c:994
#, c-format
msgid "PL/Python function \"%s\" failed"
msgstr "PL/Python-Funktion »%s« fehlgeschlagen"

#: plpython.c:1064
#, c-format
msgid ""
"PyList_SetItem() failed for PL/Python function \"%s\" while setting up "
"arguments"
msgstr ""
"PyList_SetItem() fehlgeschlagen für PL/Python-Funktion »%s«, beim Einrichten "
"der Argumente"

#: plpython.c:1068
#, c-format
msgid ""
"PyDict_SetItemString() failed for PL/Python function \"%s\" while setting up "
"arguments"
msgstr ""
"PyDict_SetItemString() fehlgeschlagen für PL/Python-Funktion »%s«, beim "
"Einrichten der Argumente"

#: plpython.c:1139
msgid "PyCObject_AsVoidPtr() failed"
msgstr "PyCObject_AsVoidPtr() fehlgeschlagen"

#: plpython.c:1248
msgid "trigger functions can only be called as triggers"
msgstr "Triggerfunktionen können nur als Trigger aufgerufen werden"

#: plpython.c:1252
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "PL/Python-Funktionen können keinen Rückgabetyp %s haben"

#: plpython.c:1331
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "PL/Python-Funktionen können Typ %s nicht annehmen"

#: plpython.c:1370
msgid "PyCObject_FromVoidPtr() failed"
msgstr "PyCObject_FromVoidPtr() fehlgeschlagen"

#: plpython.c:1428
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "konnte PL/Python-Funktion »%s« nicht kompilieren"

#: plpython.c:1740
msgid "could not create new dictionary"
msgstr "konnte neues Dictionary nicht erzeugen"

#: plpython.c:1827 plpython.c:1916 plpython.c:1987
msgid "could not compute string representation of Python object"
msgstr "konnte Zeichenkettendarstellung eines Python-Objekts nicht berechnen"

#: plpython.c:1841
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "Schlüssel »%s« nicht in Mapping gefunden"

#: plpython.c:1842
msgid ""
"To return null in a column, add the value None to the mapping with the key "
"named after the column."
msgstr ""
"Um einen NULL-Wert in einer Spalte zurückzugeben, muss der Wert None mit "
"einem nach der Spalte benannten Schlüssel in das Mapping eingefügt werden."

#: plpython.c:1886
msgid "length of returned sequence did not match number of columns in row"
msgstr ""
"Länge der zurückgegebenen Sequenz hat nicht mit der Anzahl der Spalten in "
"der Zeile übereingestimmt"

#: plpython.c:2000
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "Attribut »%s« existiert nicht in Python-Objekt"

#: plpython.c:2001
msgid ""
"To return null in a column, let the returned object have an attribute named "
"after column with value None."
msgstr ""
"Um einen NULL-Wert in einer Spalte zurückzugeben, muss das zurückzugebende "
"Objekt ein nach der Spalte benanntes Attribut mit dem Wert None haben."

#: plpython.c:2223
msgid "plan.status takes no arguments"
msgstr "plan.status nimmt keine Argumente"

#: plpython.c:2353 plpython.c:2492
msgid "transaction aborted"
msgstr "Transaktion abgebrochen"

#: plpython.c:2360
msgid "invalid arguments for plpy.prepare"
msgstr "ungültige Argumente für plpy.prepare"

#: plpython.c:2367
msgid "second argument of plpy.prepare must be a sequence"
msgstr "zweites Argument von plpy.prepare muss eine Sequenz sein"

#: plpython.c:2412
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: Typname auf Position %d ist keine Zeichenkette"

#: plpython.c:2439
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare unterstützt keine zusammengesetzten Datentypen"

#: plpython.c:2467
msgid "unrecognized error in PLy_spi_prepare"
msgstr "unbekannter Fehler in PLy_spi_prepare"

#: plpython.c:2469 plpython.c:2633 plpython.c:2680
#, c-format
msgid "in PL/Python function \"%s\""
msgstr "in PL/Python-Funktion »%s«"

#: plpython.c:2505
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute hat eine Anfrage oder einen Plan erwartet"

#: plpython.c:2522
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute nimmt eine Sequenz als zweites Argument"

#: plpython.c:2538 plpython.c:2567
#, c-format
msgid "PL/Python function \"%s\" could not execute plan"
msgstr "PL/Python-Funktion »%s« konnte Plan nicht ausführen"

#: plpython.c:2542
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Sequenz aus %d Argument erwartet, aber %d erhalten: %s"
msgstr[1] "Sequenz aus %d Argumenten erwartet, aber %d erhalten: %s"

#: plpython.c:2631
msgid "unrecognized error in PLy_spi_execute_plan"
msgstr "unbekanneter Fehler in PLy_spi_execute_plan"

#: plpython.c:2652
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan fehlgeschlagen: %s"

#: plpython.c:2678
msgid "unrecognized error in PLy_spi_execute_query"
msgstr "unbekannter Fehler in PLy_spi_execute_query"

#: plpython.c:2689
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute fehlgeschlagen: %s"

#: plpython.c:2746
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "unbekannter Fehler in PLy_spi_execute_fetch_result"

#: plpython.c:2786
msgid "untrapped error in initialization"
msgstr "nicht abgefangener Fehler bei der Initialisierung"

#: plpython.c:2789
msgid "could not create procedure cache"
msgstr "konnte Prozedur-Cache nicht erzeugen"

#: plpython.c:2801
msgid "could not import \"__main__\" module"
msgstr "konnte Modul »__main__« nicht importieren"

#: plpython.c:2808
msgid "could not initialize globals"
msgstr "konnte globale Objekte nicht initialisieren"

#: plpython.c:2910
msgid "could not parse error message in plpy.elog"
msgstr "konnte Fehlermeldung in plpy.elog nicht parsen"

#: plpython.c:3029
#, c-format
msgid "PL/Python: %s"
msgstr "PL/Python: %s"

#: plpython.c:3030
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:3120
msgid "out of memory"
msgstr "Speicher aufgebraucht"
