# German message translation file for plpython
# Copyright (C) 2009 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# Peter Eisentraut <peter_e@gmx.net>, 2009.
#
# $Id: plpython.po,v 1.1 2009/01/20 09:59:38 petere Exp $
#
# Use these quotes: »%s«
#
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 8.4\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2009-01-20 10:41+0200\n"
"PO-Revision-Date: 2009-01-20 11:55+0200\n"
"Last-Translator: Peter Eisentraut <peter_e@gmx.net>\n"
"Language-Team: German <peter_e@gmx.net>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: plpython.c:420 plpython.c:445
msgid "unexpected return value from trigger procedure"
msgstr "unerwarteter Rückgabewert von Triggerprozedur"

#: plpython.c:421
msgid "Expected None or a string."
msgstr "Erwartete None oder eine Zeichenkette."

#: plpython.c:435
msgid ""
"PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "PL/Python-Funktion gab in einem DELETE-Trigger \"MODIFY\" zurück -- ignoriert"

#: plpython.c:446
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Erwartete None, \"OK\", \"SKIP\" oder \"MODIFY\"."

#: plpython.c:493
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] wurde gelöscht, kann Zeile nicht ändern"

#: plpython.c:496
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] ist kein Dictionary"

#: plpython.c:515
#, c-format
msgid "name of TD[\"new\"] attribute at ordinal position %d is not a string"
msgstr "Name des Attributs auf Position %d in TD[\"new\"] ist keine Zeichenkette"

#: plpython.c:519
#, c-format
msgid ""
"key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering "
"row"
msgstr "in TD[\"new\"] gefundener Schlüssel »%s« existiert nicht als Spalte in der den Trigger auslösenden Zeile"

#: plpython.c:540
#, c-format
msgid ""
"could not compute string representation of Python object in PL/Python "
"function \"%s\" while modifying trigger row"
msgstr "konnte Zeichenkettendarstellung eines Python-Objekts nicht berechnen, in PL/Python-Funktion »%s«, beim Ändern der Triggerzeile"

#: plpython.c:622
msgid "could not create new dictionary while building trigger arguments"
msgstr "konnte neues Dictionary nicht erzeugen, beim Aufbauen der Triggerargumente"

#: plpython.c:830
msgid "unsupported set function return mode"
msgstr "nicht unterstützter Rückgabemodus für Funktion mit Mengenergebnis"

#: plpython.c:831
msgid ""
"PL/Python set-returning functions only support returning only value per call."
msgstr "PL/Python unterstützt für Funktionen mit Mengenergebnis nur das Zurückgeben von einem Wert pro Aufruf."

#: plpython.c:843
msgid "returned object cannot be iterated"
msgstr "zurückgegebenes Objekt kann nicht iteriert werden"

#: plpython.c:844
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "PL/Python-Funktionen mit Mengenergebnis müssen ein iterierbares Objekt zurückgeben."

#: plpython.c:872
msgid "error fetching next item from iterator"
msgstr "Fehler beim Auslesen des nächsten Elements vom Iterator"

#: plpython.c:890
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "PL/Python-Funktion mit Rückgabetyp »void« hat nicht None zurückgegeben"

#: plpython.c:937
#, c-format
msgid ""
"could not create string representation of Python object in PL/Python "
"function \"%s\" while creating return value"
msgstr "konnte Zeichenkettendarstellung eines Python-Objekts nicht erzeugen, in PL/Python-Funktion »%s«, beim Erzeugen des Rückgabewerts"

#: plpython.c:986
#, c-format
msgid "PL/Python function \"%s\" failed"
msgstr "PL/Python-Funktion »%s« fehlgeschlagen"

#: plpython.c:1058
#, c-format
msgid ""
"PyDict_SetItemString() failed for PL/Python function \"%s\" while setting up "
"arguments"
msgstr "PyDict_SetItemString() fehlgeschlagen für PL/Python-Funktion »%s«, beim Einrichten der Argumente"

#: plpython.c:1235
msgid "trigger functions can only be called as triggers"
msgstr "Triggerfunktionen können nur als Trigger aufgerufen werden"

#: plpython.c:1239
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "PL/Python-Funktionen können keinen Rückgabetyp %s haben"

#: plpython.c:1318
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "PL/Python-Funktionen können Typ %s nicht annehmen"

#: plpython.c:1412
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "konnte PL/Python-Funktion »%s« nicht kompilieren"

#: plpython.c:1724
msgid "could not create new dictionary"
msgstr "konnte neues Dictionary nicht erzeugen"

#: plpython.c:1811 plpython.c:1900 plpython.c:1971
msgid "could not compute string representation of Python object"
msgstr "konnte Zeichenkettendarstellung eines Python-Objekts nicht berechnen"

#: plpython.c:1825
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "Schlüssel »%s« nicht in Mapping gefunden"

#: plpython.c:1826
msgid ""
"To return null in a column, add the value None to the mapping with the key "
"named after the column."
msgstr "Um einen NULL-Wert in einer Spalte zurückzugeben, muss der Wert None mit einem nach der Spalte benannten Schlüssel in das Mapping eingefügt werden."

#: plpython.c:1870
msgid "length of returned sequence did not match number of columns in row"
msgstr "Länge der zurückgegebenen Sequenz hat nicht mit der Anzahl der Spalten in der Zeile übereingestimmt"

#: plpython.c:1984
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "Attribut »%s« existiert nicht in Python-Objekt"

#: plpython.c:1985
msgid ""
"To return null in a column, let the returned object have an attribute named "
"after column with value None."
msgstr "Um einen NULL-Wert in einer Spalte zurückzugeben, muss das zurückzugebende Objekt ein nach der Spalte benanntes Attribut mit dem Wert None haben."

#: plpython.c:2207
msgid "plan.status takes no arguments"
msgstr "plan.status nimmt keine Argumente"

#: plpython.c:2337 plpython.c:2476
msgid "transaction aborted"
msgstr "Transaktion abgebrochen"

#: plpython.c:2344
msgid "invalid arguments for plpy.prepare"
msgstr "ungültige Argumente für plpy.prepare"

#: plpython.c:2351
msgid "second argument of plpy.prepare must be a sequence"
msgstr "zweites Argument von plpy.prepare muss eine Sequenz sein"

#: plpython.c:2396
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: Typname auf Position %d ist keine Zeichenkette"

#: plpython.c:2423
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare unterstützt keine zusammengesetzten Datentypen"

#: plpython.c:2451
msgid "unrecognized error in PLy_spi_prepare"
msgstr "unbekannter Fehler in PLy_spi_prepare"

#: plpython.c:2453 plpython.c:2615 plpython.c:2662
#, c-format
msgid "in PL/Python function \"%s\""
msgstr "in PL/Python-Funktion »%s«"

#: plpython.c:2489
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute hat eine Anfrage oder einen Plan erwartet"

#: plpython.c:2506
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute nimmt eine Sequenz als zweites Argument"

#: plpython.c:2522 plpython.c:2549
#, c-format
msgid "PL/Python function \"%s\" could not execute plan"
msgstr "PL/Python-Funktion »%s« konnte Plan nicht ausführen"

#: plpython.c:2526
#, c-format
msgid "Expected sequence of %d arguments, got %d: %s"
msgstr "Sequenz aus %d Argumenten erwartet, aber %d erhalten: %s"

#: plpython.c:2613
msgid "unrecognized error in PLy_spi_execute_plan"
msgstr "unbekanneter Fehler in PLy_spi_execute_plan"

#: plpython.c:2634
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan fehlgeschlagen: %s"

#: plpython.c:2660
msgid "unrecognized error in PLy_spi_execute_query"
msgstr "unbekannter Fehler in PLy_spi_execute_query"

#: plpython.c:2671
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute fehlgeschlagen: %s"

#: plpython.c:2731
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "unbekannter Fehler in PLy_spi_execute_fetch_result"

#: plpython.c:2767
msgid "untrapped error in initialization"
msgstr "nicht abgefangener Fehler bei der Initialisierung"

#: plpython.c:2770
msgid "could not create procedure cache"
msgstr "konnte Prozedur-Cache nicht erzeugen"

#: plpython.c:2782
msgid "could not import \"__main__\" module"
msgstr "konnte Modul »__main__« nicht importieren"

#: plpython.c:2789
msgid "could not initialize globals"
msgstr "konnte globale Objekte nicht initialisieren"

#: plpython.c:2891
msgid "could not parse error message in plpy.elog"
msgstr "konnte Fehlermeldung in plpy.elog nicht parsen"

#: plpython.c:2987
#, c-format
msgid "PL/Python: %s"
msgstr "PL/Python: %s"

#: plpython.c:2988
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:3078
msgid "out of memory"
msgstr "Speicher aufgebraucht"
