#
# Translation of plpython to Italian
# PostgreSQL Project
#
# Associazione Culturale ITPUG - Italian PostgreSQL Users Group
# http://www.itpug.org/ - info@itpug.org
#
# Traduttori:
#  * Flavio Spada <f.spada@sbv.mi.it>
#  * Daniele Varrazzo <daniele.varrazzo@gmail.com
#
# Revisori:
#  * Gabriele Bartolini <gabriele.bartolini@2ndQuadrant.it>
#
# Copyright (c) 2010, Associazione Culturale ITPUG
# Distributed under the same license of the PostgreSQL project
#
msgid ""
msgstr ""
"Project-Id-Version: plpython (PostgreSQL) 8.4\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2013-01-29 13:18+0000\n"
"PO-Revision-Date: 2012-11-02 15:26+0100\n"
"Last-Translator: Daniele Varrazzo <daniele.varrazzo@gmail.com>\n"
"Language-Team: Gruppo traduzioni ITPUG <traduzioni@itpug.org>\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Poedit 1.5.4\n"

#: plpython.c:428 plpython.c:453
msgid "unexpected return value from trigger procedure"
msgstr "la prodedura trigger ha restituito un valore inatteso"

#: plpython.c:429
msgid "Expected None or a string."
msgstr "Atteso None o una stringa."

#: plpython.c:443
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "la funzione trigger PL/Python ha restituito \"MODIFY\" in un trigger DELETE -- ignorato"

#: plpython.c:454
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Atteso None, \"OK\", \"SKIP\", o \"MODIFY\"."

#: plpython.c:501
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] cancellato, non è possibile modificare la riga"

#: plpython.c:504
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] non è un dizionario"

#: plpython.c:523
#, c-format
msgid "name of TD[\"new\"] attribute at ordinal position %d is not a string"
msgstr "il nome dell'attributo TD[\"new\"] in posizione %d non è una stringa"

#: plpython.c:527
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr "la chiave \"%s\" trovata in TD[\"new\"] non esiste come colonna nella riga del trigger"

#: plpython.c:548
#, c-format
msgid "could not compute string representation of Python object in PL/Python function \"%s\" while modifying trigger row"
msgstr "impossibile ottenere la rappresentazione stringa dell'oggetto Python nella funzione PL/Python \"%s\" nella modifica della riga del trigger"

#: plpython.c:630
msgid "could not create new dictionary while building trigger arguments"
msgstr "creazione del nuovo dizionario nella costruzione degli argomenti del trigger fallita"

#: plpython.c:837
msgid "unsupported set function return mode"
msgstr "modalità di ritorno della funzione set non supportata"

#: plpython.c:838
msgid "PL/Python set-returning functions only support returning only value per call."
msgstr "le funzioni PL/Python che restituiscono insiemi supportano solo la restituzione di un solo valore per chiamata."

#: plpython.c:850
msgid "returned object cannot be iterated"
msgstr "l'oggetto restituito non può essere iterato"

#: plpython.c:851
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "le funzioni PL/Python che restituiscono insiemi devono restituire un oggetto iterabile"

#: plpython.c:879
msgid "error fetching next item from iterator"
msgstr "errore nell'ottenere l'elemento successivo dall'iteratore"

#: plpython.c:910
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "la funzione PL/Python che restituisce \"void\" non ha restituito None"

#: plpython.c:957
#, c-format
msgid "could not create string representation of Python object in PL/Python function \"%s\" while creating return value"
msgstr "impossibile ottenere la rappresentazione stringa dell'oggetto Python nella funzione PL/Python \"%s\" nella creazione del valore di ritorno"

#: plpython.c:1006
#, c-format
msgid "PL/Python function \"%s\" failed"
msgstr "errore nella funzione PL/Python \"%s\""

#: plpython.c:1076
#, c-format
msgid "PyList_SetItem() failed for PL/Python function \"%s\" while setting up arguments"
msgstr "PyList_SetItem() fallita per la funzione PL/Python \"%s\" durante la preparazione degli argomenti"

#: plpython.c:1080
#, c-format
msgid "PyDict_SetItemString() failed for PL/Python function \"%s\" while setting up arguments"
msgstr "PyDict_SetItemString() fallita per la funzione PL/Python \"%s\" durante la preparazione degli argomenti"

#: plpython.c:1151
msgid "PyCObject_AsVoidPtr() failed"
msgstr "PyCObject_AsVoidPtr() fallita"

#: plpython.c:1260
msgid "trigger functions can only be called as triggers"
msgstr "le funzioni trigger possono essere chiamate esclusivamente da trigger"

#: plpython.c:1264
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "le funzioni PL/Python non possono restituire il tipo %s"

#: plpython.c:1343
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "le funzioni PL/Python non possono accettare il tipo %s"

#: plpython.c:1382
msgid "PyCObject_FromVoidPtr() failed"
msgstr "PyCObject_FromVoidPtr() fallita"

#: plpython.c:1440
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "compilazione della funzione PL/Python \"%s\" fallita"

#: plpython.c:1752
msgid "could not create new dictionary"
msgstr "creazione del nuovo dizionario fallita"

#: plpython.c:1839 plpython.c:1928 plpython.c:1999
msgid "could not compute string representation of Python object"
msgstr "impossibile ottenere la rappresentazione stringa dell'oggetto Python"

#: plpython.c:1853
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "la chiave \"%s\" non è stata trovata nel dizionario"

#: plpython.c:1854
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr "Per restituire null in una colonna, inserire nella mappa il valore None con una chiave chiamata come la colonna."

#: plpython.c:1898
msgid "length of returned sequence did not match number of columns in row"
msgstr "la lunghezza della sequenza ritornata non rispetta il numero di colonne presenti nella riga"

#: plpython.c:2012
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "l'attributo \"%s\" non esiste nell'oggetto Python"

#: plpython.c:2013
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr "Per restituire null in una colonna, l'oggetto restituito deve avere un attributo chiamato come la colonna con valore None."

#: plpython.c:2235
msgid "plan.status takes no arguments"
msgstr "plan.status non accetta argomenti"

#: plpython.c:2360 plpython.c:2499
msgid "transaction aborted"
msgstr "transazione interrotta"

#: plpython.c:2367
msgid "invalid arguments for plpy.prepare"
msgstr "argomenti non validi per plpy.prepare"

#: plpython.c:2374
msgid "second argument of plpy.prepare must be a sequence"
msgstr "il secondo argomento di plpy.prepare deve essere una sequenza"

#: plpython.c:2419
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: il nome del tipo nella posizione %d non è una stringa"

#: plpython.c:2446
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare non supporta tipi compositi"

#: plpython.c:2474
msgid "unrecognized error in PLy_spi_prepare"
msgstr "errore sconosciuto in PLy_spi_prepare"

#: plpython.c:2476 plpython.c:2640 plpython.c:2687
#, c-format
msgid "in PL/Python function \"%s\""
msgstr "nella funzione PL/Python \"%s\""

#: plpython.c:2512
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute si aspetta una query o un plan"

#: plpython.c:2529
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute richiede una sequenza come secondo argomento"

#: plpython.c:2545 plpython.c:2574
#, c-format
msgid "PL/Python function \"%s\" could not execute plan"
msgstr "errore nell'esecuzione del piano nella funzione PL/Python \"%s\""

#: plpython.c:2549
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Attesa sequenza di %d argomento, ricevuti %d: %s"
msgstr[1] "Attesa sequenza di %d argomenti, ricevuti %d: %s"

#: plpython.c:2638
msgid "unrecognized error in PLy_spi_execute_plan"
msgstr "errore sconosciuto in PLy_spi_execute_plan"

#: plpython.c:2659
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan ha fallito: %s"

#: plpython.c:2685
msgid "unrecognized error in PLy_spi_execute_query"
msgstr "errore sconosciuto in PLy_spi_execute_query"

#: plpython.c:2696
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute ha fallito: %s"

#: plpython.c:2753
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "errore sconosciuto nella funzione PLy_spi_execute_fetch_result"

#: plpython.c:2793
msgid "untrapped error in initialization"
msgstr "errore non catturato durante l'inizializzazione"

#: plpython.c:2796
msgid "could not create procedure cache"
msgstr "creazione della cache delle procedure fallita"

#: plpython.c:2808
msgid "could not import \"__main__\" module"
msgstr "importazione del modulo \"__main__\""

#: plpython.c:2815
msgid "could not initialize globals"
msgstr "inizializzazione delle variabili globali fallita"

#: plpython.c:2917
msgid "could not parse error message in plpy.elog"
msgstr "non è stato possibile interpretare il messaggio di errore in plpy.elog"

#: plpython.c:3036
#, c-format
msgid "PL/Python: %s"
msgstr "PL/Python: %s"

#: plpython.c:3037
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:3127
msgid "out of memory"
msgstr "memoria esaurita"
