# Spanish message translation file for plpython
#
# Copyright (C) 2009-2012 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
#
# Emanuel Calvo Franco <postgres.arg@gmail.com>, 2009.
# Alvaro Herrera <alvherre@alvh.no-ip.org>, 2009-2012
#
msgid ""
msgstr ""
"Project-Id-Version: plpython (PostgreSQL 9.1)\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2012-05-29 18:39+0000\n"
"PO-Revision-Date: 2012-02-21 22:54-0300\n"
"Last-Translator: Alvaro Herrera <alvherre@alvh.no-ip.org>\n"
"Language-Team: PgSQL-es-Ayuda <pgsql-es-ayuda@postgresql.org>\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"

#: plpython.c:476
#, c-format
msgid "PL/Python function \"%s\""
msgstr "función PL/Python «%s»"

#: plpython.c:483
msgid "PL/Python anonymous code block"
msgstr "bloque de código anónimo de PL/Python"

#: plpython.c:490
msgid "while modifying trigger row"
msgstr "mientras se modificaba la fila de disparador"

#: plpython.c:497
msgid "while creating return value"
msgstr "mientras se creaba el valor de retorno"

#: plpython.c:708 plpython.c:734
msgid "unexpected return value from trigger procedure"
msgstr "valor de retorno no esperado desde el procedimiento disparador"

#: plpython.c:709
msgid "Expected None or a string."
msgstr "Se esperaba None o una cadena."

#: plpython.c:724
msgid ""
"PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""
"función de disparador de PL/Python retorno «MODIFY» en un disparador de tipo "
"DELETE -- ignorado"

#: plpython.c:735
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Se esperaba None, «OK», «SKIP» o «MODIFY»."

#: plpython.c:787
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] borrado, no se puede modicar el registro"

#: plpython.c:790
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] no es un diccionario"

#: plpython.c:814
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr ""
"el nombre del atributo de TD[\"new\"] en la posición %d no es una cadena"

#: plpython.c:820
#, c-format
msgid ""
"key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering "
"row"
msgstr ""
"la llave «%s» en TD[\"new\"] no existe como columna en la fila disparadora"

#: plpython.c:916
msgid "could not create new dictionary while building trigger arguments"
msgstr ""
"no se pudo crear un nuevo diccionario mientras se construían los argumentos "
"de disparador"

#: plpython.c:1123
msgid "unsupported set function return mode"
msgstr "modo de retorno de conjunto de función no soportado"

#: plpython.c:1124
msgid ""
"PL/Python set-returning functions only support returning only value per call."
msgstr ""
"Las funciones PL/Python que retornan conjuntos sólo permiten retornar un "
"valor por invocación."

#: plpython.c:1136
msgid "returned object cannot be iterated"
msgstr "objeto retornado no puede ser iterado"

#: plpython.c:1137
msgid "PL/Python set-returning functions must return an iterable object."
msgstr ""
"Los funciones PL/Python que retornan conjuntos deben retornar un objeto "
"iterable."

#: plpython.c:1162
msgid "error fetching next item from iterator"
msgstr "error extrayendo el próximo elemento del iterador"

#: plpython.c:1197
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "función PL/Python con tipo de retorno «void» no retorna None"

# FIXME not very happy with this
#: plpython.c:1277
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "abortando una subtransacción que no se ha cerrado"

#: plpython.c:1393
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "PyList_SetItem() falló, mientras se inicializaban los argumentos"

#: plpython.c:1397
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "PyDict_SetItemString() falló, mientras se inicializaban los argumentos"

#: plpython.c:1409
msgid ""
"function returning record called in context that cannot accept type record"
msgstr ""
"se llamó una función que retorna un registro en un contexto que no puede "
"aceptarlo"

#: plpython.c:1643
msgid "trigger functions can only be called as triggers"
msgstr "las funciones disparadoras sólo pueden ser llamadas como disparadores"

#: plpython.c:1648 plpython.c:2121
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "las funciones PL/Python no pueden retornar el tipo %s"

#: plpython.c:1730
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "la funciones PL/Python no pueden aceptar el tipo %s"

#: plpython.c:1826
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "no se pudo compilar la función PL/Python «%s»"

#: plpython.c:1829
msgid "could not compile anonymous PL/Python code block"
msgstr "no se pudo compilar el bloque anónimo PL/Python"

#: plpython.c:2123
msgid "PL/Python does not support conversion to arrays of row types."
msgstr "PL/Python no soporta la conversión de arrays a tipos de registro."

#: plpython.c:2332
msgid "cannot convert multidimensional array to Python list"
msgstr "no se puede convertir array multidimensional a una lista Python"

#: plpython.c:2333
msgid "PL/Python only supports one-dimensional arrays."
msgstr "PL/Python sólo soporta arrays unidimensionales."

#: plpython.c:2339
msgid "could not create new list"
msgstr "no se pudo crear una nueva lista"

#: plpython.c:2374
msgid "could not create new dictionary"
msgstr "no se pudo crear un nuevo diccionario"

#: plpython.c:2471
msgid "could not create bytes representation of Python object"
msgstr "no se pudo crear la representación de cadena de bytes de Python"

#: plpython.c:2563
msgid "could not create string representation of Python object"
msgstr ""
"no se pudo crear la representación de cadena de texto del objeto de Python"

#: plpython.c:2574
msgid ""
"could not convert Python object into cstring: Python string representation "
"appears to contain null bytes"
msgstr ""
"no se pudo convertir el objeto Python a un cstring: la representación de "
"cadena Python parece tener bytes nulos (\\0)"

#: plpython.c:2608
msgid ""
"return value of function with array return type is not a Python sequence"
msgstr ""
"el valor de retorno de la función con tipo de retorno array no es una "
"secuencia Python"

#: plpython.c:2708
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "la llave «%s» no fue encontrada en el mapa"

#: plpython.c:2709
msgid ""
"To return null in a column, add the value None to the mapping with the key "
"named after the column."
msgstr ""
"Para retornar null en una columna, agregue el valor None al mapa, con llave "
"llamada igual que la columna."

#: plpython.c:2757
msgid "length of returned sequence did not match number of columns in row"
msgstr ""
"el tamaño de la secuencia retornada no concuerda con el número de columnas "
"de la fila"

#: plpython.c:2865
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "el atributo «%s» no existe en el objeto Python"

#: plpython.c:2866
msgid ""
"To return null in a column, let the returned object have an attribute named "
"after column with value None."
msgstr ""
"Para retornar null en una columna, haga que el objeto retornado tenga un "
"atributo llamado igual que la columna, con valor None."

#: plpython.c:3185
msgid "plan.status takes no arguments"
msgstr "plan.status no lleva argumentos"

#: plpython.c:3309
msgid "second argument of plpy.prepare must be a sequence"
msgstr "el segundo argumento de plpy.prepare debe ser una secuencia"

#: plpython.c:3359
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: el nombre de tipo en la posición %d no es una cadena"

#: plpython.c:3391
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare no soporta tipos compuestos"

#: plpython.c:3481
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute espera una consulta o un plan"

#: plpython.c:3500
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute lleva una secuencia como segundo argumento"

#: plpython.c:3516
msgid "could not execute plan"
msgstr "no se pudo ejecutar el plan"

#: plpython.c:3519
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Se esperaba una secuencia de %d argumento, se obtuvo %d: %s"
msgstr[1] "Se esperaba una secuencia de %d argumentos, se obtuvo %d: %s"

#: plpython.c:3661
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "falló SPI_execute_plan: %s"

#: plpython.c:3740
#, c-format
msgid "SPI_execute failed: %s"
msgstr "falló SPI_execute: %s"

#: plpython.c:3795
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "error desconocido en PLy_spi_execute_fetch_result"

#: plpython.c:3857
msgid "this subtransaction has already been entered"
msgstr "ya se ha entrado en esta subtransacción"

#: plpython.c:3863 plpython.c:3915
msgid "this subtransaction has already been exited"
msgstr "ya se ha salido de esta subtransacción"

#: plpython.c:3909
msgid "this subtransaction has not been entered"
msgstr "no se ha entrado en esta subtransacción"

#: plpython.c:3921
msgid "there is no subtransaction to exit from"
msgstr "no hay una subtransacción de la cual salir"

#: plpython.c:3980 plpython.c:3984
msgid "could not generate SPI exceptions"
msgstr "no se pudo generar excepciones SPI"

#: plpython.c:4009
msgid "could not add the spiexceptions module"
msgstr "no se pudo importar el módulo spiexceptions"

#: plpython.c:4029
msgid "could not create the base SPI exceptions"
msgstr "no se pudo crear las excepciones SPI basales"

#: plpython.c:4097
msgid "Python major version mismatch in session"
msgstr "las versiones mayores de Python no coinciden en esta sesión"

#: plpython.c:4098
#, c-format
msgid ""
"This session has previously used Python major version %d, and it is now "
"attempting to use Python major version %d."
msgstr ""
"Esta sesión ha usado previamente la versión mayor de Python %d, y ahora está "
"intentando usar la versión mayor %d."

#: plpython.c:4100
msgid "Start a new session to use a different Python major version."
msgstr ""
"Inicie una nueva sesión para usar una versión mayor de Python diferente."

#: plpython.c:4115
msgid "untrapped error in initialization"
msgstr "error no capturado en la inicialización"

#: plpython.c:4143
msgid "could not import \"__main__\" module"
msgstr "no se pudo importar el módulo «__main__»"

#: plpython.c:4148
msgid "could not create globals"
msgstr "no se pudo crear las globales"

#: plpython.c:4152
msgid "could not initialize globals"
msgstr "no se pudo inicializar las globales"

#: plpython.c:4190 plpython.c:4193
msgid "could not import \"plpy\" module"
msgstr "no se pudo importar el módulo «plpy»"

#: plpython.c:4260
msgid "could not unpack arguments in plpy.elog"
msgstr "no se pudo desempaquetar los argumentos de plpy.elog"

#: plpython.c:4268
msgid "could not parse error message in plpy.elog"
msgstr "no se pudo analizar el mensaje de error de plpy.elog"

#: plpython.c:4292 plpython.c:4526 plpython.c:4527
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:4885
msgid "could not convert Python Unicode object to PostgreSQL server encoding"
msgstr ""
"no se pudo convertir el objeto Unicode de Python a la codificación de "
"servidor de PostgreSQL"
