# Russian message translation file for plpython
# Copyright (C) 2012 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# Alexander Lakhin <exclusion@gmail.com>, 2012.
#
# ChangeLog:
#
#   - April 3, 2012: Bug fixes. Alexander Lakhin <exclusion@gmail.com>.
#   - February 25, 2012: Backporting to 8.4. Alexander Lakhin <exclusion@gmail.com>.
#   - February 18, 2012: Complete translation for 9.1. Alexander Lakhin <exclusion@gmail.com>.
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 8.4\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2012-07-10 22:40+0000\n"
"PO-Revision-Date: 2012-04-03 08:53+0400\n"
"Last-Translator: Alexander Lakhin <exclusion@gmail.com>\n"
"Language-Team: Russian <pgtranslation-translators@pgfoundry.org>\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"
"X-Generator: Lokalize 1.4\n"

#: plpython.c:428 plpython.c:453
msgid "unexpected return value from trigger procedure"
msgstr "триггерная процедура вернула недопустимое значение"

#: plpython.c:429
msgid "Expected None or a string."
msgstr "Ожидалось None или строка."

#: plpython.c:443
msgid ""
"PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""
"триггерная функция PL/Python вернула \"MODIFY\" в триггере DELETE -- "
"игнорируется"

#: plpython.c:454
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Ожидалось None, \"OK\", \"SKIP\" или \"MODIFY\"."

#: plpython.c:501
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "элемент TD[\"new\"] удалён -- изменить строку нельзя"

#: plpython.c:504
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] - не словарь"

#: plpython.c:523
#, c-format
msgid "name of TD[\"new\"] attribute at ordinal position %d is not a string"
msgstr "имя атрибута TD[\"new\"] с порядковым номером %d не является строкой"

#: plpython.c:527
#, c-format
msgid ""
"key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering "
"row"
msgstr ""
"ключу \"%s\", найденному в TD[\"new\"], не соответствует колонка в строке, "
"обрабатываемой триггером"

#: plpython.c:548
#, c-format
msgid ""
"could not compute string representation of Python object in PL/Python "
"function \"%s\" while modifying trigger row"
msgstr ""
"не удалось представить объект Python в виде текстовой строки в функции PL/"
"Python \"%s\" при изменении строки в триггере"

#: plpython.c:630
msgid "could not create new dictionary while building trigger arguments"
msgstr "не удалось создать словарь для передачи аргументов триггера"

#: plpython.c:837
msgid "unsupported set function return mode"
msgstr "неподдерживаемый режим возврата для функции с результатом-множеством"

#: plpython.c:838
msgid ""
"PL/Python set-returning functions only support returning only value per call."
msgstr ""
"Функции PL/Python с результатом-множеством могут возвращать только по одному "
"значению за вызов."

#: plpython.c:850
msgid "returned object cannot be iterated"
msgstr "возвращаемый объект не поддерживает итерации"

#: plpython.c:851
msgid "PL/Python set-returning functions must return an iterable object."
msgstr ""
"Функции PL/Python с результатом-множеством должны возвращать объекты с "
"возможностью итерации."

#: plpython.c:879
msgid "error fetching next item from iterator"
msgstr "ошибка получения следующего элемента из итератора"

#: plpython.c:910
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "функция PL/Python с типом результата \"void\" вернула не None"

#: plpython.c:957
#, c-format
msgid ""
"could not create string representation of Python object in PL/Python "
"function \"%s\" while creating return value"
msgstr ""
"не удалось представить объект Python в виде текстовой строки в функции PL/"
"Python \"%s\" при формировании возвращаемого значения"

#: plpython.c:1006
#, c-format
msgid "PL/Python function \"%s\" failed"
msgstr "ошибка в функции PL/Python \"%s\""

#: plpython.c:1076
#, c-format
msgid ""
"PyList_SetItem() failed for PL/Python function \"%s\" while setting up "
"arguments"
msgstr ""
"ошибка в PyList_SetItem() для функции PL/Python \"%s\" при настройке "
"аргументов"

#: plpython.c:1080
#, c-format
msgid ""
"PyDict_SetItemString() failed for PL/Python function \"%s\" while setting up "
"arguments"
msgstr ""
"ошибка в PyDict_SetItemString() для функции PL/Python \"%s\" при настройке "
"аргументов"

#: plpython.c:1151
msgid "PyCObject_AsVoidPtr() failed"
msgstr "ошибка в PyCObject_AsVoidPtr()"

#: plpython.c:1260
msgid "trigger functions can only be called as triggers"
msgstr "триггерные функции могут вызываться только в триггерах"

#: plpython.c:1264
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "функции PL/Python не могут возвращать тип %s"

#: plpython.c:1343
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "функции PL/Python не могут принимать тип %s"

#: plpython.c:1382
msgid "PyCObject_FromVoidPtr() failed"
msgstr "ошибка в PyCObject_FromVoidPtr()"

#: plpython.c:1440
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "не удалось скомпилировать функцию PL/Python \"%s\""

#: plpython.c:1752
msgid "could not create new dictionary"
msgstr "не удалось создать словарь"

#: plpython.c:1839 plpython.c:1928 plpython.c:1999
msgid "could not compute string representation of Python object"
msgstr "не удалось получить строковое представление объекта Python"

#: plpython.c:1853
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "ключ \"%s\" не найден в сопоставлении"

#: plpython.c:1854
msgid ""
"To return null in a column, add the value None to the mapping with the key "
"named after the column."
msgstr ""
"Чтобы присвоить колонке NULL, добавьте в сопоставление значение None с "
"ключом-именем колонки."

#: plpython.c:1898
msgid "length of returned sequence did not match number of columns in row"
msgstr "длина возвращённой последовательности не равна числу колонок в строке"

#: plpython.c:2012
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "в объекте Python не существует атрибут \"%s\""

#: plpython.c:2013
msgid ""
"To return null in a column, let the returned object have an attribute named "
"after column with value None."
msgstr ""
"Чтобы присвоить колонке NULL, присвойте возвращаемому значению атрибут с "
"именем колонки и значением None."

#: plpython.c:2235
msgid "plan.status takes no arguments"
msgstr "plan.status не принимает аргументы"

#: plpython.c:2360 plpython.c:2499
msgid "transaction aborted"
msgstr "транзакция прервана"

#: plpython.c:2367
msgid "invalid arguments for plpy.prepare"
msgstr "неверные аргументы plpy.prepare"

#: plpython.c:2374
msgid "second argument of plpy.prepare must be a sequence"
msgstr "вторым аргументом plpy.prepare должна быть последовательность"

#: plpython.c:2419
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: имя типа с порядковым номером %d не является строкой"

#: plpython.c:2446
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare не поддерживает составные типы"

#: plpython.c:2474
msgid "unrecognized error in PLy_spi_prepare"
msgstr "нераспознанная ошибка в PLy_spi_prepare"

#: plpython.c:2476 plpython.c:2640 plpython.c:2687
#, c-format
msgid "in PL/Python function \"%s\""
msgstr "в функции PL/Python \"%s\""

#: plpython.c:2512
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute ожидает запрос или план"

#: plpython.c:2529
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute принимает в качестве второго аргумента последовательность"

#: plpython.c:2545 plpython.c:2574
#, c-format
msgid "PL/Python function \"%s\" could not execute plan"
msgstr "функция PL/Python \"%s\" не может выполнять план"

#: plpython.c:2549
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Ожидалась последовательность из %d аргумента, получено %d: %s"
msgstr[1] "Ожидалась последовательность из %d аргументов, получено %d: %s"
msgstr[2] "Ожидалась последовательность из %d аргументов, получено %d: %s"

#: plpython.c:2638
msgid "unrecognized error in PLy_spi_execute_plan"
msgstr "нераспознанная ошибка в PLy_spi_execute_plan"

#: plpython.c:2659
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "ошибка в SPI_execute_plan: %s"

#: plpython.c:2685
msgid "unrecognized error in PLy_spi_execute_query"
msgstr "нераспознанная ошибка в PLy_spi_execute_query"

#: plpython.c:2696
#, c-format
msgid "SPI_execute failed: %s"
msgstr "ошибка в SPI_execute: %s"

#: plpython.c:2753
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "нераспознанная ошибка в PLy_spi_execute_fetch_result"

#: plpython.c:2793
msgid "untrapped error in initialization"
msgstr "необработанная ошибка при инициализации"

#: plpython.c:2796
msgid "could not create procedure cache"
msgstr "не удалось создать процедурный кэш"

#: plpython.c:2808
msgid "could not import \"__main__\" module"
msgstr "не удалось импортировать модуль \"__main__\""

#: plpython.c:2815
msgid "could not initialize globals"
msgstr "не удалось инициализировать глобальные данные"

#: plpython.c:2917
msgid "could not parse error message in plpy.elog"
msgstr "не удалось разобрать сообщение об ошибке в plpy.elog"

#: plpython.c:3036
#, c-format
msgid "PL/Python: %s"
msgstr "PL/Python: %s"

#: plpython.c:3037
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:3127
msgid "out of memory"
msgstr "нехватка памяти"
